SELECT CITY, LENGTH(CITY) FROM
(SELECT * FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) AS MN FROM STATION)
ORDER BY CITY)
WHERE ROWNUM = 1;
SELECT CITY, LENGTH(CITY) FROM
(SELECT * FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) AS MX FROM STATION)
ORDER BY CITY)
WHERE ROWNUM = 1;